apiVersion: v1
kind: Pod
metadata:
  name: postgresql-and-liquibase
spec:
  containers:
  - name: postgres
    image: postgres:latest
    ports:
    - containerPort: 5432
    env:
    - name: POSTGRES_DB
      value: test
    - name: POSTGRES_USER
      value: postgress
    - name: POSTGRES_PASSWORD
      value: postgress
  # initContainers:
  - name: liquibase
    image: liquibase/liquibase:latest
    command: [
      "liquibase", 
      "update", 
      "--changeLogFile=db-changelog.xml", 
      "--url=jdbc:postgresql://localhost:5432/test?user=postgress&password=postgress",
      "--log-level=FINE",
    ]
    env:
    - name: LIQUIBASE_SEARCH_PATH
      value: /liquibase/changelog
    volumeMounts:
    - name: liquibase-changelog-volume
      mountPath: /liquibase/changelog
  volumes:
  - name: liquibase-changelog-volume
    configMap:
      name: liquibase-changelog


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: liquibase-changelog
data:
  db-changelog.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
                       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                       xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
                       http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.3.xsd">
      <changeSet id="1" author="John Doe">
        <sql>CREATE TABLE example (
            id SERIAL PRIMARY KEY,
            name VARCHAR(255) NOT NULL
        );</sql>
      </changeSet>
    </databaseChangeLog>